name: Push

on:
  push:
    branches: [ "develop", "master" ]
    pull_request:
      branches: [ "develop", "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
              distribution: 'temurin' # See 'Supported distributions' for available options
              java-version : 17
              name : Build with Gradle
              run : ./gradlew build

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Upload HTML test report
        uses: actions/upload-artifact@v2
        with:
          name: index.html
          path: app/build/reports/lint-result-debug.html
