name: Push

on:
  push:
    branches: [ "develop", "master" ]
    pull_request:
      branches: [ "develop", "master" ]
  workflow_dispatch:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
              distribution: 'temurin' # See 'Supported distributions' for available options
              java-version : 17
              name : Build with Gradle
              run : ./gradlew build

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Upload HTML test report
        uses: actions/upload-artifact@v2
        with:
          name: lint.html
          path: app/build/reports/lint-results-debug.html

  unit-test:
     needs: [lint]
     runs-on: ubuntu-latest
     strategy:
       matrix:
         java-version: [ 8, 11, 15 ]

       steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-java@v1
           with:
             java-version: ${{ matrix.java-version }}
         - run: mvn -B install --no-transfer-progress --file pom.xml
     steps:
       - name: checkout the code
         uses: actions/checkout@v2

       - name: run tests
         run: ./gradlew test

       - name: upload test reports
         uses: actions/checkout@v2
         with:
             name: unit_test_reports
             path: app/build/reports/tests/testDebugUnitTest/
